### PR TITLE
Improved Strict Rule to handle more complex cases

### LINKED ISSUE #17: Doesn't give warning in return case
**NOTE**: See the added example below for more details.

I had expected the following example to give a warning, but it doesn't:

`using System.Threading.Tasks;

namespace ACF.UI.LoanOrigination.Gateway
{

	public interface ICallee
	{
		bool ProblemSolved { get; }
		Task<int> SolveProblemAsync();
	}

	public class Callee : ICallee
	{
		public bool ProblemSolved { get; set; }

		public async Task<int> SolveProblemAsync()
		{
			await Task.Delay(10);
			ProblemSolved = true;
			return 1;
		}
	}

	public class Caller
	{
		public bool DoCall()
		{
			ICallee xxx = new Callee();

			// This analyser will give a warning at the following line
			var i = xxx.SolveProblemAsync(); // This is most likely an undesired fire and forget. 

			return xxx.ProblemSolved; // Will return false - we expected it to return true
		}
	}
}
`
It's not a "fire and forget", but I'd like to know that I missed the await here.

### PR DESCRIPTION
**Pull request by samusaran**
Following the issue #17, this are the proposed changes.

The last commit include the fix for the light bulb crash.

### CODE REVIEW

**Comment by ykoksen** [comment]
I've looked at this during the last couple of days. And I'm rather impressed and happy about it. However I just tried it in more or less the same scenario that made the light bulb crash, and in my opinion there are still some problems.

Code example:
~~~~
   

1.  class Program : ITest
2.     {
3.         static ITest test = new Program();
4. 
5.         static async Task Main(string[] args)
6.         {
7.             Console.WriteLine("Hello World!");
8. 
9.             Task test2 = test.TestThis();
10. 
11.             await Task.WhenAll(test2, test.TestThis());
12.         }
13. 
14.         public async Task<string> TestThis()
15.         {
16.             await File.AppendAllLinesAsync("test.txt", new []{ "Test"});
17.             return "Hugo";
18.         }
19.     }
20. 
21.     public interface ITest
22.     {
23.         Task<string> TestThis();
24.     }

~~~~

The above example is perfectly valid code - however the analyser now gives a warning on line 9. If you allow the light-bulbs to fix it the line will be replaced with: 
`Task test2 = await test.TestThis();`
This results in code which now doesn't compile. But the analyser still believes there is a problem and therefore still shows the warning. And apparently the light-bulb auto fix for the whole line (including the part that now contains an error) will result in this analysers auto fix running again resulting in yet another  `await` (`Task test2 = await await test.TestThis();`).

I'm in a bit of doubt as to what the best solution might be. But I believe that the level should be decreased to `Info`. And maybe there should not be an option to try to automatically fix it.

**Comment by samusaran** [comment]
I'm happy you liked it :D 
I think the issue is in those specific situations:
`Task t = test.TestThis()`
and
`var result = test.TestThis()`

While the first explicitly wants a Task as a result from the method, it's the second case that is abiguous and may need `await`. I definitely need to handle the first case and not provide a code fix when the code specifically want a Task back. It should be trivial to implement.

While on the Info\Warning debate, we could set a lower level, my objective still remain to provide a reliable way to let the user know that a Task might be unawaited. One thing I would not do is to disable the inspection by default, because it "hides" the feature from the user. It's instead easier to just see the inspection and disable completely (Resharper\Rider users are already used to that approach). Issue #17 was the example.

I'll let you know!

**Review by ykoksen — CHANGES_REQUESTED** [review]
Just writing the same as I wrote in a comment but more formal as an actual review:

I've looked at this during the last couple of days. And I'm rather impressed and happy about it. However I just tried it in more or less the same scenario that made the light bulb crash, and in my opinion there are still some problems.

Code example:
~~~~
   

1.  class Program : ITest
2.     {
3.         static ITest test = new Program();
4. 
5.         static async Task Main(string[] args)
6.         {
7.             Console.WriteLine("Hello World!");
8. 
9.             Task test2 = test.TestThis();
10. 
11.             await Task.WhenAll(test2, test.TestThis());
12.         }
13. 
14.         public async Task<string> TestThis()
15.         {
16.             await File.AppendAllLinesAsync("test.txt", new []{ "Test"});
17.             return "Hugo";
18.         }
19.     }
20. 
21.     public interface ITest
22.     {
23.         Task<string> TestThis();
24.     }

~~~~

The above example is perfectly valid code - however the analyser now gives a warning on line 9. If you allow the light-bulbs to fix it the line will be replaced with: 
`Task test2 = await test.TestThis();`
This results in code which now doesn't compile. But the analyser still believes there is a problem and therefore still shows the warning. And apparently the light-bulb auto fix for the whole line (including the part that now contains an error) will result in this analysers auto fix running again resulting in yet another  `await` (`Task test2 = await await test.TestThis();`).

I'm in a bit of doubt as to what the best solution might be. But I believe that the level should be decreased to `Info`. And maybe there should not be an option to try to automatically fix it.

**Comment by samusaran** [comment]
I will get to you in a couple of days ok? I will try to find a solution about it (like if the task is passed to a function that requires a task, the task will probably be handled by that function)

**Comment by ykoksen** [comment]
@samusaran it seems you never got around to making the changes. I'll likely delete this pull request in a couple of weeks if no updates are made.

**Comment by samusaran** [comment]
I'm sorry but I left my old job and I'm currently working on completely different things that keeps me occupied. Feel free to handle the pull request as you wish.

Thank you for your work!

**Comment by ykoksen** [comment]
This have been closed due to inactivity.

**Pull request closed without merging**
