### PR TITLE
Add support for missing awaits in null-conditional expressions

### LINKED ISSUE #45: Null-conditional operator prevents the analyzer to correctly detect a missed await
This scenario is **not detected**:

```cs
myNullableObject?.DoSomethingAsync();
```

when re-written this way, it works correctly:
```cs
var o = myNullableObject;
if(o != null)
   o.DoSomethingAsync();
```

### PR DESCRIPTION
**Pull request by fszewczy**
The goal of this PR is to add support for null-conditionals, described in #34.

To do list:
- [x] Add tests for conditional expressions with Task
- [x] Add tests for conditional expressions with ValueTask
- [x] Add tests for auto code fix
- [x] Prepare solution

### CODE REVIEW

**Comment by ykoksen** [comment]
Could you add a test for the conditional expression when an automatic code fix is applied?

**Comment by ykoksen** [comment]
Since you've made a checklist I presume that I'm not to approve the PR or look to much into it until all three are checked?

**Comment by fszewczy** [comment]
Yes, so far I have only added tests for Task, I would like to add tests for ValueTask and - mentioned by you - automatic code fix (added to the list).
I tested these cases on my own and the solution worked, but the tests must be added.

I didn't have time to deal with this over the weekend, I think I can add the tests tomorrow night.

**Comment by ykoksen** [comment]
Sure - no worry and no hurry :-)

**Comment by fszewczy** [comment]
The detection of problematic expressions is ready - IMO analyzer works fine. 

Unfortunately proposing a fixup is as easy and I have to think about all the cases, especially in strict rule mode - this may take a while.

**Comment by DarthSonic** [comment]
Can you please review this task? I'm waiting for it ;-)

**Comment by fszewczy** [comment]
Sorry for leaving this PR in this state...

Detecting missing awaits in null-conditional expressions is done, but an automatic code fix is not implemented.

I started to implement an auto code fix in a private branch, but I had to stop because of lack of time, then - shame to admit - I forgot about this PR. 

Auto fix for this case is not trivial. For example code:
`var task2 = xxx?.DoSomethingAsync();`
should be corrected to such
`var task2 = await ( xxx?.DoSomethingAsync() ?? Task.FromResult(default(int)) )`
It gets harder when conditional expressions are longer.
I cannot promise that I will be able to complete this feature, certainly not soon.

@ykoksen , maybe we can separate 'auto code fix' from this PR and create a separate PR for it?

**Comment by ykoksen** [comment]
Yeah, that would be an ok option. 

Can I review it now, or is there anything else left?

**Comment by fszewczy** [comment]
You can review it. Do I have to resolve conflicts now or after a review?

**Comment by ykoksen** [comment]
I just had a look and I think you need to resolve the conflicts before I can do a proper review. Sorry for keeping you waiting.

**Comment by EikeSchwass** [comment]
@fszewczy @ykoksen any timeline when this will be ready?

**Comment by fszewczy** [comment]
I did a rebase, tests pass. I wanted to test this version additionally, but unfortunately, I have no time for that at the moment. 

@ykoksen, can you review the changes in this PR?

**Review by ykoksen — APPROVED** [review]

**Pull request merged**
